apiVersion: v1
data:
  mirrors: |
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller: gcriotekton/pipeline-controller
kind: ConfigMap
metadata:
  name: mirror-config
  namespace: system
