name: Backup Git repository

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  BackupBinary:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
      id: go
    - uses: actions/checkout@v3.0.2
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.4.1
      with:
        version: latest
        args: release --rm-dist --snapshot
  BackupGit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: backup
      uses: jenkins-zh/git-backup-actions@v0.0.4
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        TARGET_GIT: "git@gitee.com:linuxsuren/mirrors.git"
