name: SyncImage

on:
  schedule:
  - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download tool
      run: |
        wget -O image.tar.gz https://github.com/AliyunContainerService/image-syncer/releases/download/v1.3.0/image-syncer-v1.3.0-linux-amd64.tar.gz
        tar xzvf image.tar.gz
    - name: Sync Image
      run: |
        git clone https://linuxsuren:${{ secrets.GH_PASS }}@github.com/LinuxSuRen/private
        cp private/rick/config.json auth.json
        ls -ahl
        export PATH=$PATH:.
        image-syncer --proc=6 --auth=auth.json --images=images.json --namespace=jenkinszh --registry=registry.cn-beijing.aliyuncs.com --retries=3
