name: SyncImage

on:
  schedule:
  - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download tool
      run: |
        wget -O image.tar.gz https://github.com/LinuxSuRen/image-syncer/releases/download/v1.3.1.1/image-syncer-v1.3.1.1-linux-amd64.tar.gz
        tar xzvf image.tar.gz
    - name: Sync Image
      run: |
        echo ${{ secrets.CONFIG }} | base64 -d > auth.json
        export PATH=$PATH:.
        image-syncer --proc=6 --auth=auth.json --images=images.json --namespace=jenkinszh --registry=registry.cn-beijing.aliyuncs.com --retries=3
